# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Chord DHT Implementation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
  build-and-push-docker-image:
      needs: build
      runs-on: ubuntu-latest

      steps:
        - name: Generate Version
          uses: paulhatch/semantic-version@v5.4.0
          id: version
          with:
            tag_prefix: "v"
            major_pattern: "(MAJOR)"
            minor_pattern: "(MINOR)"
            version_format: "${major}.${minor}.${patch}-${increment}"
            namespace: chord_dht
      
        - name: Checkout repo
          uses: actions/checkout@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build Docker image
          run: |
            docker build -t chord-dht-img:${{ steps.version.outputs.version }} .
        
        - name: Login to Docker Hub
          run: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        - name: Tag docker image
          run: |
            docker tag chord-dht-img:${{ steps.version.outputs.version }} ${{secrets.DOCKER_USERNAME}}/chord_dht_repo:${{ steps.version.outputs.version }}
            
        - name: Push docker image
          run: |
            docker push ${{secrets.DOCKER_USERNAME}}/chord_dht_repo:${{ steps.version.outputs.version }}
